package com.aereolinea.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PasajeroAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasajeroAllPropertiesEquals(Pasajero expected, Pasajero actual) {
        assertPasajeroAutoGeneratedPropertiesEquals(expected, actual);
        assertPasajeroAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasajeroAllUpdatablePropertiesEquals(Pasajero expected, Pasajero actual) {
        assertPasajeroUpdatableFieldsEquals(expected, actual);
        assertPasajeroUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasajeroAutoGeneratedPropertiesEquals(Pasajero expected, Pasajero actual) {
        assertThat(expected)
            .as("Verify Pasajero auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasajeroUpdatableFieldsEquals(Pasajero expected, Pasajero actual) {
        assertThat(expected)
            .as("Verify Pasajero relevant properties")
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getApellido()).as("check apellido").isEqualTo(actual.getApellido()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getTelefono()).as("check telefono").isEqualTo(actual.getTelefono()))
            .satisfies(e -> assertThat(e.getFechaNacimiento()).as("check fechaNacimiento").isEqualTo(actual.getFechaNacimiento()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasajeroUpdatableRelationshipsEquals(Pasajero expected, Pasajero actual) {
        // empty method
    }
}
