package com.aereolinea.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReservaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservaAllPropertiesEquals(Reserva expected, Reserva actual) {
        assertReservaAutoGeneratedPropertiesEquals(expected, actual);
        assertReservaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservaAllUpdatablePropertiesEquals(Reserva expected, Reserva actual) {
        assertReservaUpdatableFieldsEquals(expected, actual);
        assertReservaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservaAutoGeneratedPropertiesEquals(Reserva expected, Reserva actual) {
        assertThat(expected)
            .as("Verify Reserva auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservaUpdatableFieldsEquals(Reserva expected, Reserva actual) {
        assertThat(expected)
            .as("Verify Reserva relevant properties")
            .satisfies(e -> assertThat(e.getCodigo()).as("check codigo").isEqualTo(actual.getCodigo()))
            .satisfies(e -> assertThat(e.getFechaReserva()).as("check fechaReserva").isEqualTo(actual.getFechaReserva()))
            .satisfies(e -> assertThat(e.getEstado()).as("check estado").isEqualTo(actual.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservaUpdatableRelationshipsEquals(Reserva expected, Reserva actual) {
        assertThat(expected)
            .as("Verify Reserva relationships")
            .satisfies(e -> assertThat(e.getVuelo()).as("check vuelo").isEqualTo(actual.getVuelo()))
            .satisfies(e -> assertThat(e.getAsiento()).as("check asiento").isEqualTo(actual.getAsiento()))
            .satisfies(e -> assertThat(e.getPasajero()).as("check pasajero").isEqualTo(actual.getPasajero()));
    }
}
