package com.aereolinea.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VueloAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVueloAllPropertiesEquals(Vuelo expected, Vuelo actual) {
        assertVueloAutoGeneratedPropertiesEquals(expected, actual);
        assertVueloAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVueloAllUpdatablePropertiesEquals(Vuelo expected, Vuelo actual) {
        assertVueloUpdatableFieldsEquals(expected, actual);
        assertVueloUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVueloAutoGeneratedPropertiesEquals(Vuelo expected, Vuelo actual) {
        assertThat(expected)
            .as("Verify Vuelo auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVueloUpdatableFieldsEquals(Vuelo expected, Vuelo actual) {
        assertThat(expected)
            .as("Verify Vuelo relevant properties")
            .satisfies(e -> assertThat(e.getNumeroVuelo()).as("check numeroVuelo").isEqualTo(actual.getNumeroVuelo()))
            .satisfies(e -> assertThat(e.getOrigen()).as("check origen").isEqualTo(actual.getOrigen()))
            .satisfies(e -> assertThat(e.getDestino()).as("check destino").isEqualTo(actual.getDestino()))
            .satisfies(e -> assertThat(e.getFechaSalida()).as("check fechaSalida").isEqualTo(actual.getFechaSalida()))
            .satisfies(e -> assertThat(e.getFechaLlegada()).as("check fechaLlegada").isEqualTo(actual.getFechaLlegada()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVueloUpdatableRelationshipsEquals(Vuelo expected, Vuelo actual) {
        // empty method
    }
}
