services:
  mysql:
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=aerolineavirtual
      - MYSQL_USER=aero
      - MYSQL_PASSWORD=aero
      - MYSQL_ROOT_HOST=%
    ports:
      - '3307:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-uroot', '-proot']
      interval: 5s
      timeout: 5s
      retries: 30
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
